version: "3.7"

services:
  lb:
    image: nginx:1.21
    container_name: load-balancer-container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - nuocsach-publicweb
    restart: always
    networks:
      - nuocsach-network

  nuocsach-publicweb:
    image: chungndict/app-nuoc-sach-report:1.0.5
    container_name: app-nuoc-sach-report-container
    environment:
      - ASPNETCORE_URLS=http://+:80;
      - App__SelfUrl=https://nuocsach.erpuni.vn
      - ConnectionStrings__MySqlConnection=server=172.16.1.189;user=root;password=123456;database=nuocsach_report_new;
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    networks:
      - nuocsach-network
networks:
  nuocsach-network:
    external: true
